# Generated by Django 5.1 on 2024-08-30 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nota_disciplina', to='notas.disciplina'),
        ),
    ]
