# Generated by Django 5.0.6 on 2024-08-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_usuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
